import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import * as crypto from 'node:crypto';
import type {
  AnimationsOutput,
  AssetManifest,
  DOMNode,
  DomExtractResult,
  HoverDiff,
} from '../types/index.js';

export type GeneratorFormat = 'vite' | 'nextjs';

export interface GenerateReactAppOptions {
  format?: GeneratorFormat;
}

export async function generateReactApp(
  outputDir: string,
  options: GenerateReactAppOptions = {},
): Promise<void> {
  const format: GeneratorFormat = options.format ?? 'vite';
  if (format === 'nextjs') {
    throw new Error(
      'Next.js output is not implemented yet — re-run with --format vite for now.',
    );
  }

  const dom = await readJson<DomExtractResult>(path.join(outputDir, 'dom-tree.json'));
  const animations = await readJson<AnimationsOutput>(path.join(outputDir, 'animations.json'));
  const manifest =
    (await readJson<AssetManifest>(path.join(outputDir, 'assets', 'manifest.json'))) ?? {};

  if (!dom) throw new Error('dom-tree.json not found — run the extractor first');

  const urlToPublic = new Map<string, string>();
  for (const [url, rec] of Object.entries(manifest)) {
    urlToPublic.set(url, '/' + rec.localPath.replace(/\\/g, '/'));
  }

  const appearIds = new Set(animations?.whileInViewCandidates ?? []);
  const hoverBySelector = new Map<string, HoverDiff>();
  for (const h of animations?.hoverStates ?? []) hoverBySelector.set(h.selector, h);

  const body = findBody(dom.tree) ?? dom.tree;
  const components = collectComponents(body);

  // Split each top-level body child into its own SectionN component so Page.tsx
  // stays well under Babel's per-function JSX size threshold. Each section is
  // emitted as an independent file with its own registered classes.
  const sections: ComponentDefinition[] = [];
  let sectionIdx = 1;
  for (const child of body.children) {
    if (SKIP_TAGS.has(child.tag)) continue;
    if (components.idToName.has(child.id)) continue;
    if (countElements(child) < 3) continue;
    const name = `Section${sectionIdx++}`;
    sections.push({ name, node: child });
    components.idToName.set(child.id, name);
  }

  const componentsDir = path.join(outputDir, 'src', 'components');
  await fs.mkdir(componentsDir, { recursive: true });

  const styleRegistry = newStyleRegistry();
  const allDefs = [...components.definitions, ...sections];

  for (const def of allDefs) {
    const ctx = newCtx(
      urlToPublic,
      appearIds,
      hoverBySelector,
      components.idToName,
      styleRegistry,
    );
    const jsx = emit(def.node, ctx, 2, { skipRootSubstitution: true });
    const file = renderComponentFile(def.name, jsx, ctx, false);
    await fs.writeFile(path.join(componentsDir, `${def.name}.tsx`), file);
  }

  // Emit Page component
  const pageCtx = newCtx(
    urlToPublic,
    appearIds,
    hoverBySelector,
    components.idToName,
    styleRegistry,
  );
  const pageJsx = emit(body, pageCtx, 2, { skipRootSubstitution: true });
  const pageFile = renderComponentFile('Page', pageJsx, pageCtx, true);
  await fs.writeFile(path.join(componentsDir, 'Page.tsx'), pageFile);

  // Generated stylesheet with all extracted style classes
  const stylesDir = path.join(outputDir, 'src', 'styles');
  await fs.mkdir(stylesDir, { recursive: true });
  await fs.writeFile(path.join(stylesDir, 'generated.css'), renderGeneratedCss(styleRegistry));

  // Copy assets → public
  await copyDir(path.join(outputDir, 'assets'), path.join(outputDir, 'public', 'assets'));

  // Scaffold project files
  await writeScaffold(outputDir);
}

function countElements(node: DOMNode): number {
  let n = 1;
  for (const c of node.children) n += countElements(c);
  return n;
}

// ---------- Style registry ----------

interface StyleRegistry {
  classByKey: Map<string, string>;
  ordered: Array<{ className: string; declarations: string }>;
}

function newStyleRegistry(): StyleRegistry {
  return { classByKey: new Map(), ordered: [] };
}

function registerStyle(
  reg: StyleRegistry,
  style: Record<string, string>,
): string | null {
  const keys = Object.keys(style);
  if (keys.length === 0) return null;
  keys.sort();
  const declarations = keys.map((k) => `${k}: ${style[k]}`).join('; ');
  const existing = reg.classByKey.get(declarations);
  if (existing) return existing;
  const hash = crypto.createHash('sha1').update(declarations).digest('hex').slice(0, 8);
  const className = `fe-${hash}`;
  reg.classByKey.set(declarations, className);
  reg.ordered.push({ className, declarations });
  return className;
}

function renderGeneratedCss(reg: StyleRegistry): string {
  const lines = [
    '/* Generated by framer-extract — deduped style classes extracted from computed styles */',
    '',
  ];
  for (const { className, declarations } of reg.ordered) {
    lines.push(`.${className} { ${declarations}; }`);
  }
  return lines.join('\n') + '\n';
}

// ---------- Context ----------

interface GenCtx {
  urlToPublic: Map<string, string>;
  appearIds: Set<string>;
  hoverBySelector: Map<string, HoverDiff>;
  componentMap: Map<string, string>;
  componentRefs: Set<string>;
  hasMotion: boolean;
  styleRegistry: StyleRegistry;
}

function newCtx(
  urlToPublic: Map<string, string>,
  appearIds: Set<string>,
  hoverBySelector: Map<string, HoverDiff>,
  componentMap: Map<string, string>,
  styleRegistry: StyleRegistry,
): GenCtx {
  return {
    urlToPublic,
    appearIds,
    hoverBySelector,
    componentMap,
    componentRefs: new Set(),
    hasMotion: false,
    styleRegistry,
  };
}

// ---------- Tag / attr tables ----------

const SKIP_TAGS = new Set([
  'script', 'style', 'meta', 'link', 'head', 'title', 'noscript', 'base', 'html',
]);

const VOID_TAGS = new Set([
  'img', 'br', 'hr', 'input', 'source', 'area', 'col', 'embed', 'wbr', 'track',
]);

const ATTR_RENAME: Record<string, string> = {
  class: 'className',
  for: 'htmlFor',
  tabindex: 'tabIndex',
  readonly: 'readOnly',
  maxlength: 'maxLength',
  contenteditable: 'contentEditable',
  autofocus: 'autoFocus',
  autoplay: 'autoPlay',
  crossorigin: 'crossOrigin',
  usemap: 'useMap',
  colspan: 'colSpan',
  rowspan: 'rowSpan',
  'accept-charset': 'acceptCharset',
  enctype: 'encType',
  novalidate: 'noValidate',
  srcset: 'srcSet',
};

const STYLE_ALLOWLIST = [
  'display', 'position', 'top', 'right', 'bottom', 'left',
  'width', 'height', 'min-width', 'min-height', 'max-width', 'max-height',
  'margin-top', 'margin-right', 'margin-bottom', 'margin-left',
  'padding-top', 'padding-right', 'padding-bottom', 'padding-left',
  'flex-direction', 'flex-wrap', 'flex-grow', 'flex-shrink', 'flex-basis',
  'justify-content', 'align-items', 'align-self', 'gap',
  'grid-template-columns', 'grid-template-rows',
  'color', 'background-color', 'background-image',
  'background-size', 'background-position', 'background-repeat',
  'border-top', 'border-right', 'border-bottom', 'border-left',
  'border-radius', 'box-shadow',
  'font-family', 'font-size', 'font-weight', 'font-style',
  'line-height', 'letter-spacing', 'text-align', 'text-transform', 'text-decoration-line',
  'opacity', 'transform', 'transform-origin', 'z-index',
  'overflow', 'cursor', 'aspect-ratio', 'object-fit', 'object-position',
];

const STYLE_DEFAULTS: Record<string, string[]> = {
  'margin-top': ['0px'],
  'margin-right': ['0px'],
  'margin-bottom': ['0px'],
  'margin-left': ['0px'],
  'padding-top': ['0px'],
  'padding-right': ['0px'],
  'padding-bottom': ['0px'],
  'padding-left': ['0px'],
  top: ['auto'],
  right: ['auto'],
  bottom: ['auto'],
  left: ['auto'],
  width: ['auto'],
  height: ['auto'],
  opacity: ['1'],
  'z-index': ['auto'],
  transform: ['none'],
  'transform-origin': ['50% 50%', '50% 50% 0px'],
  'background-image': ['none'],
  'background-color': ['rgba(0, 0, 0, 0)', 'transparent'],
  'background-size': ['auto'],
  'background-position': ['0% 0%'],
  'background-repeat': ['repeat'],
  'border-top': ['0px none rgb(0, 0, 0)'],
  'border-right': ['0px none rgb(0, 0, 0)'],
  'border-bottom': ['0px none rgb(0, 0, 0)'],
  'border-left': ['0px none rgb(0, 0, 0)'],
  'border-radius': ['0px'],
  'box-shadow': ['none'],
  'text-decoration-line': ['none'],
  'letter-spacing': ['normal'],
  cursor: ['auto'],
  overflow: ['visible'],
  'min-width': ['auto', '0px'],
  'min-height': ['auto', '0px'],
  'max-width': ['none'],
  'max-height': ['none'],
  'flex-grow': ['0'],
  'flex-shrink': ['1'],
  'flex-basis': ['auto'],
  'aspect-ratio': ['auto'],
  'object-fit': ['fill'],
  'object-position': ['50% 50%'],
  'font-style': ['normal'],
  'font-weight': ['400'],
  'font-size': ['16px'],
  'line-height': ['normal'],
  'text-transform': ['none'],
  'text-align': ['start'],
  'flex-direction': ['row'],
  'flex-wrap': ['nowrap'],
  'justify-content': ['normal', 'flex-start'],
  'align-items': ['normal', 'stretch'],
  gap: ['normal', '0px'],
};

const TAILWIND_MAP: Record<string, Record<string, string>> = {
  display: {
    flex: 'flex',
    grid: 'grid',
    none: 'hidden',
    block: 'block',
    'inline-block': 'inline-block',
    inline: 'inline',
    'inline-flex': 'inline-flex',
  },
  position: {
    absolute: 'absolute',
    relative: 'relative',
    fixed: 'fixed',
    sticky: 'sticky',
    static: 'static',
  },
  'flex-direction': {
    row: 'flex-row',
    column: 'flex-col',
    'row-reverse': 'flex-row-reverse',
    'column-reverse': 'flex-col-reverse',
  },
  'flex-wrap': {
    wrap: 'flex-wrap',
    nowrap: 'flex-nowrap',
    'wrap-reverse': 'flex-wrap-reverse',
  },
  'justify-content': {
    center: 'justify-center',
    'flex-start': 'justify-start',
    'flex-end': 'justify-end',
    'space-between': 'justify-between',
    'space-around': 'justify-around',
    'space-evenly': 'justify-evenly',
  },
  'align-items': {
    center: 'items-center',
    'flex-start': 'items-start',
    'flex-end': 'items-end',
    stretch: 'items-stretch',
    baseline: 'items-baseline',
  },
  'text-align': {
    center: 'text-center',
    left: 'text-left',
    right: 'text-right',
    justify: 'text-justify',
  },
  overflow: {
    hidden: 'overflow-hidden',
    auto: 'overflow-auto',
    scroll: 'overflow-scroll',
    visible: 'overflow-visible',
  },
  'text-transform': {
    uppercase: 'uppercase',
    lowercase: 'lowercase',
    capitalize: 'capitalize',
    none: 'normal-case',
  },
};

// ---------- Component collection ----------

interface ComponentDefinition {
  name: string;
  node: DOMNode;
}

interface Components {
  definitions: ComponentDefinition[];
  idToName: Map<string, string>;
}

function collectComponents(root: DOMNode): Components {
  const byKey = new Map<string, string>();
  const definitions: ComponentDefinition[] = [];
  const idToName = new Map<string, string>();
  const usedNames = new Set<string>();

  function visit(node: DOMNode): void {
    if (node.framer?.isComponentRoot) {
      const rawName = componentNameFromNode(node);
      if (rawName) {
        const key = node.framer.componentIdentifier ?? rawName;
        let name = byKey.get(key);
        if (!name) {
          let candidate = rawName;
          let i = 2;
          while (usedNames.has(candidate)) candidate = `${rawName}${i++}`;
          name = candidate;
          usedNames.add(name);
          byKey.set(key, name);
          definitions.push({ name, node });
        }
        idToName.set(node.id, name);
      }
    }
    for (const c of node.children) visit(c);
  }

  visit(root);
  return { definitions, idToName };
}

function componentNameFromNode(node: DOMNode): string | null {
  const f = node.framer;
  if (!f) return null;
  const raw = f.name || f.componentIdentifier;
  if (!raw) return null;
  const cleaned = raw.replace(/[^a-zA-Z0-9]/g, '');
  if (!cleaned) return null;
  const pascal = cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
  return /^[0-9]/.test(pascal) ? `C${pascal}` : pascal;
}

function findBody(node: DOMNode): DOMNode | null {
  if (node.tag === 'body') return node;
  for (const c of node.children) {
    const hit = findBody(c);
    if (hit) return hit;
  }
  return null;
}

// ---------- JSX emission ----------

interface EmitOpts {
  skipRootSubstitution: boolean;
}

function emit(node: DOMNode, ctx: GenCtx, indent: number, opts: EmitOpts): string {
  if (SKIP_TAGS.has(node.tag)) return '';

  const compName = ctx.componentMap.get(node.id);
  if (compName && !opts.skipRootSubstitution) {
    ctx.componentRefs.add(compName);
    return `${pad(indent)}<${compName} />`;
  }

  const pad1 = pad(indent);
  const useMotion = !!node.framer?.appearId && ctx.appearIds.has(node.framer.appearId);
  if (useMotion) ctx.hasMotion = true;
  const baseTag = node.tag;
  const tagName = useMotion ? `motion.${baseTag}` : baseTag;

  const { tailwindClasses, inlineStyle } = convertStyles(node.computedStyle, ctx.urlToPublic);
  const classParts = [...tailwindClasses];
  const generatedClass = registerStyle(ctx.styleRegistry, inlineStyle);
  if (generatedClass) classParts.push(generatedClass);
  const attrParts: string[] = [];

  for (const [k, v] of Object.entries(node.attributes)) {
    if (k === 'data-extract-id') continue;
    if (k.startsWith('data-framer-')) continue;
    if (k.startsWith('on')) continue;
    if (k === 'style') continue;
    if (k === 'class') {
      if (v) classParts.unshift(v);
      continue;
    }
    if (k === 'src' || k === 'href' || k === 'poster') {
      const resolved = ctx.urlToPublic.get(v) ?? v;
      attrParts.push(`${jsxAttrName(k)}=${jsxAttrValue(resolved)}`);
      continue;
    }
    if (k === 'srcset') {
      attrParts.push(`srcSet=${jsxAttrValue(rewriteSrcset(v, ctx.urlToPublic))}`);
      continue;
    }
    attrParts.push(`${jsxAttrName(k)}=${jsxAttrValue(v)}`);
  }

  if (classParts.length > 0) {
    attrParts.unshift(`className=${jsxAttrValue(classParts.join(' '))}`);
  }

  if (useMotion) {
    attrParts.push('initial={{ opacity: 0, y: 20 }}');
    attrParts.push('whileInView={{ opacity: 1, y: 0 }}');
    attrParts.push('viewport={{ once: true, margin: "-10%" }}');
    attrParts.push('transition={{ duration: 0.6, ease: "easeOut" }}');
  }

  const headAttrs = attrParts.length > 0 ? ' ' + attrParts.join(' ') : '';

  if (VOID_TAGS.has(node.tag)) {
    return `${pad1}<${tagName}${headAttrs} />`;
  }

  const childStrings: string[] = [];
  if (node.text) {
    childStrings.push(`${pad(indent + 1)}${escapeJsxText(node.text)}`);
  }
  for (const child of node.children) {
    const s = emit(child, ctx, indent + 1, { skipRootSubstitution: false });
    if (s) childStrings.push(s);
  }

  if (childStrings.length === 0) {
    return `${pad1}<${tagName}${headAttrs} />`;
  }

  return `${pad1}<${tagName}${headAttrs}>\n${childStrings.join('\n')}\n${pad1}</${tagName}>`;
}

function pad(n: number): string {
  return '  '.repeat(n);
}

function jsxAttrName(k: string): string {
  return ATTR_RENAME[k] ?? k;
}

function jsxAttrValue(v: string): string {
  if (v.includes('"') || v.includes('\n') || v.includes('\\')) {
    return `{${JSON.stringify(v)}}`;
  }
  return `"${v}"`;
}

function escapeJsxText(s: string): string {
  if (/[{}<>]/.test(s)) return `{${JSON.stringify(s)}}`;
  return s.replace(/&/g, '&amp;');
}

function rewriteSrcset(value: string, urlToPublic: Map<string, string>): string {
  return value
    .split(',')
    .map((entry) => {
      const trimmed = entry.trim();
      if (!trimmed) return '';
      const parts = trimmed.split(/\s+/);
      const url = parts[0]!;
      const rest = parts.slice(1).join(' ');
      const resolved = urlToPublic.get(url) ?? url;
      return rest ? `${resolved} ${rest}` : resolved;
    })
    .filter(Boolean)
    .join(', ');
}

function rewriteCssUrls(value: string, urlToPublic: Map<string, string>): string {
  return value.replace(/url\(\s*(['"]?)([^'")]+)\1\s*\)/g, (_m, q: string, u: string) => {
    const resolved = urlToPublic.get(u) ?? u;
    return `url(${q}${resolved}${q})`;
  });
}

function convertStyles(
  cs: Record<string, string>,
  urlToPublic: Map<string, string>,
): { tailwindClasses: string[]; inlineStyle: Record<string, string> } {
  const tailwindClasses: string[] = [];
  const inlineStyle: Record<string, string> = {};

  for (const prop of STYLE_ALLOWLIST) {
    const raw = cs[prop];
    if (raw == null || raw === '') continue;
    if (STYLE_DEFAULTS[prop]?.includes(raw)) continue;

    const tw = TAILWIND_MAP[prop]?.[raw];
    if (tw) {
      tailwindClasses.push(tw);
      continue;
    }

    const value =
      prop === 'background-image' || prop === 'background'
        ? rewriteCssUrls(raw, urlToPublic)
        : raw;
    inlineStyle[prop] = value;
  }

  return { tailwindClasses, inlineStyle };
}

// ---------- File rendering ----------

function renderComponentFile(name: string, jsx: string, ctx: GenCtx, isPage: boolean): string {
  const lines: string[] = [];
  if (ctx.hasMotion) lines.push(`import { motion } from "framer-motion";`);
  for (const comp of ctx.componentRefs) {
    if (comp !== name) lines.push(`import ${comp} from "./${comp}";`);
  }
  if (lines.length > 0) lines.push('');
  lines.push(`export default function ${name}() {`);
  lines.push(`  return (`);
  lines.push(jsx);
  lines.push(`  );`);
  lines.push(`}`);
  lines.push('');
  // Silence unused when the page has no embedded components
  if (isPage && ctx.componentRefs.size === 0 && !ctx.hasMotion) {
    // nothing extra
  }
  return lines.join('\n');
}

// ---------- Project scaffolding ----------

async function writeScaffold(outputDir: string): Promise<void> {
  const write = (rel: string, contents: string) =>
    fs.mkdir(path.dirname(path.join(outputDir, rel)), { recursive: true }).then(() =>
      fs.writeFile(path.join(outputDir, rel), contents),
    );

  await write(
    'package.json',
    JSON.stringify(
      {
        name: 'framer-extracted-site',
        private: true,
        version: '0.0.0',
        type: 'module',
        scripts: {
          dev: 'vite',
          build: 'tsc && vite build',
          preview: 'vite preview',
        },
        dependencies: {
          react: '^18.3.1',
          'react-dom': '^18.3.1',
          'framer-motion': '^11.11.0',
        },
        devDependencies: {
          '@types/react': '^18.3.0',
          '@types/react-dom': '^18.3.0',
          '@vitejs/plugin-react': '^4.3.0',
          autoprefixer: '^10.4.20',
          postcss: '^8.4.47',
          tailwindcss: '^3.4.13',
          typescript: '^5.6.0',
          vite: '^5.4.0',
        },
      },
      null,
      2,
    ) + '\n',
  );

  await write(
    'vite.config.ts',
    `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
});
`,
  );

  await write(
    'tsconfig.json',
    JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          useDefineForClassFields: true,
          lib: ['ES2022', 'DOM', 'DOM.Iterable'],
          module: 'ESNext',
          skipLibCheck: true,
          moduleResolution: 'Bundler',
          allowImportingTsExtensions: false,
          resolveJsonModule: true,
          isolatedModules: true,
          noEmit: true,
          jsx: 'react-jsx',
          strict: true,
        },
        include: ['src'],
      },
      null,
      2,
    ) + '\n',
  );

  await write(
    'index.html',
    `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Extracted Framer Site</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`,
  );

  await write(
    'postcss.config.js',
    `export default { plugins: { tailwindcss: {}, autoprefixer: {} } };
`,
  );

  await write(
    'tailwind.config.js',
    `/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: { extend: {} },
  plugins: [],
};
`,
  );

  await write(
    'src/main.tsx',
    `import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "./styles/globals.css";

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
`,
  );

  await write(
    'src/App.tsx',
    `import Page from "./components/Page";

export default function App() {
  return <Page />;
}
`,
  );

  await write(
    'src/styles/globals.css',
    `@import "../../fonts.css";
@import "./generated.css";

@tailwind base;
@tailwind components;
@tailwind utilities;
`,
  );
}

// ---------- Utilities ----------

async function readJson<T>(file: string): Promise<T | null> {
  try {
    return JSON.parse(await fs.readFile(file, 'utf8')) as T;
  } catch {
    return null;
  }
}

async function copyDir(src: string, dest: string): Promise<void> {
  let entries: import('node:fs').Dirent[];
  try {
    entries = await fs.readdir(src, { withFileTypes: true });
  } catch {
    return;
  }
  await fs.mkdir(dest, { recursive: true });
  for (const e of entries) {
    const s = path.join(src, e.name);
    const d = path.join(dest, e.name);
    if (e.isDirectory()) await copyDir(s, d);
    else if (e.isFile()) await fs.copyFile(s, d);
  }
}
